/*******************************************************
* MODELS CLASS
* DESC: Contains models for various aircraft and vehicles
* Author: Jonathan L Clark
* Date: 5/13/2021
*******************************************************/
#ifndef _MODELS_
#define _MODELS_

#define COLOR_NAVY        0x000F      /*   0,   0, 128 */
#define COLOR_DARKGREEN   0x03E0      /*   0, 128,   0 */
#define COLOR_DARKCYAN    0x03EF      /*   0, 128, 128 */
#define COLOR_MAROON      0x7800      /* 128,   0,   0 */
#define COLOR_PURPLE      0x780F      /* 128,   0, 128 */
#define COLOR_OLIVE       0x7BE0      /* 128, 128,   0 */
#define COLOR_DARKGREY    0x7BEF      /* 128, 128, 128 */
#define COLOR_ORANGE      0xFD20      /* 255, 165,   0 */
#define COLOR_GREENYELLOW 0xAFE5      /* 173, 255,  47 */
#define COLOR_PINK        0xF81F
#define COLOR_BLACK   0x0000
#define COLOR_BLUE    0x001F
#define COLOR_RED     0xF800
#define COLOR_GREEN   0x07E0
#define COLOR_CYAN    0x07FF
#define COLOR_MAGENTA 0xF81F
#define COLOR_YELLOW  0xFFE0
#define COLOR_WHITE   0xFFFF
#define COLOR_LTGREY  0xC618
#define COLOR_DRKGREY 0x630C
#define COLOR_GREY 0x630C
#define COLOR_LTGREEN 0x04C0
#define COLOR_LIMEGREEN 0x87E0
#define COLOR_FORESTGREEN 0x2444
#define COLOR_GOLDENROD 0xDD24
#define COLOR_GREEN2 0x0400
#define COLOR_LIGHTSEAGREEN 0x2595
#define COLOR_MLRYGREEN 0x4A84
#define COLOR_SKYBLUE 0x867F

#define XWING_HEIGHT 21
#define XWING_WIDTH 24
static uint16_t xWing[] = {
COLOR_WHITE, COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_WHITE, COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_BLACK, COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_BLACK, COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_GREY,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_GREY,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_GREY,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_GREY,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLUE,   COLOR_BLUE,   COLOR_BLUE,  COLOR_BLUE,  COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_BLACK, COLOR_BLACK,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLUE,   COLOR_BLUE,   COLOR_BLUE,  COLOR_BLUE,  COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_ORANGE, COLOR_ORANGE, COLOR_BLACK, COLOR_BLACK,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_GREY,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_GREY,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_GREY,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_GREY,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_BLACK, COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_BLACK, COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_BLACK,  COLOR_BLACK,  COLOR_ORANGE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_ORANGE, COLOR_ORANGE, COLOR_ORANGE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK,  COLOR_WHITE, COLOR_WHITE,  COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,  COLOR_WHITE,  COLOR_WHITE, COLOR_WHITE,
};


#define TIE_HEIGHT 18
#define TIE_WIDTH 17
static uint16_t tieFighter[] = {
COLOR_WHITE, COLOR_WHITE, COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_WHITE, COLOR_WHITE,
COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY,  COLOR_GREY,  COLOR_GREY, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_GREY,  COLOR_BLACK, COLOR_RED,   COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY,  COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY,  COLOR_BLACK, COLOR_RED,   COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE,
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, 
COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY,  COLOR_GREY,  COLOR_GREY,
COLOR_WHITE, COLOR_WHITE, COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_GREY,  COLOR_WHITE, COLOR_WHITE,
};


#endif
